### ISSUE TITLE
Add release file signature check

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/apt-tools-prod#3]
We should aim to do release file signature verification in this repo as we do for SecureDrop prod artifacts. See the CI config over in https://github.com/freedomofpress/securedrop-apt-prod/blob/main/.circleci/config.yml for example.

**Comment by eloquence** [comment]
In SD land there are discussions to transition to GitHub actions opportunistically:
https://github.com/freedomofpress/securedrop-engineering/issues/14 (private repo for now, but will be public soon)

I would be open to doing this here as well, but since we've not widely discussed this outside the SecureDrop context yet, I'm flagging it for now and am happy to discuss more so we can take a consistent approach.

**Comment by apyrgio** [comment]
We can close this issue, since we now have signature checks:

https://github.com/freedomofpress/apt-tools-prod/blob/6e2cd0692afbd5c90e814bfe6eea0b7987575386/.github/workflows/check-packages.yml#L14-L17
